on: push
name: Test
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint
        run: yarn lint

      - name: Unit test
        run: yarn test

      # NOTE: prod. builds and deployments are done via Heroku
      #      - name: Build
      #        run: yarn build --prod

      # TODO: e2e
      #- name: E2E test
      #  run: yarn e2e

# NOTE: prod. builds and deployments are done via Heroku
#      - name: Push Build to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "dist/weerden-io/*"
#          token: ${{ secrets.TOKEN }}
